### PR TITLE
Use function_helper

### PR DESCRIPTION
**Pull request by mhvk**
This is my attempt to simply use `function_helpers`, working around the numpy bug. I think it simplifies things enough to be worthwile...

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Oh, sorry ! I'm only seeing this now and force-pushed in the interval 🙃 
Can you try to rebase this ?

**Comment by mhvk** [comment]
OK, rebased...

**Comment by neutrinoceros** [comment]
Looks nice. Let me close/re-open to trigger CI (which was previously disabled on this fork). I'll merge when green. Thank you !

**Comment by neutrinoceros** [comment]
hum, actually I don't want to go through the hassle of checking all the boxes from a fork. I can see that tests pass locally, which should be enough !

**Pull request merged**
